### ISSUE TITLE
Come up with a list of questions to be asked

### ISSUE THREAD

**Issue by DanielY-Yoo** [nyu-software-engineering/mta-google-home#12]
Keep the list of questions in this excel sheet:
https://docs.google.com/spreadsheets/d/1YTuRScYvAb4Q5tve4s7BkoZchx9RA2CXj6cgFg_4iJI/edit?usp=sharing

**Comment by bloombar** [comment]
@nyu-software-engineering/spring-2019-mta-for-google-home - this is really a spike, not a task.  Spikes are internal work for the team.  Tasks are sub-components of a work needed to be done to complete a user story.

**Comment by DanielY-Yoo** [comment]
Just changed the issue to spike and removed the task label. Thank you, professor!

**Comment by EisenHuang** [comment]
When is the L train coming in?
How long will it take for the train to get to XXX Station
what is the closest train coming in near me

**Comment by DanielY-Yoo** [comment]
Closing the issue. Registered 12 questions.
