### ISSUE TITLE
As a User, I want to know the values that created the application, and have a comprehensive documentation of how the application works.

### ISSUE THREAD

**Issue by DanielY-Yoo** [nyu-software-engineering/mta-google-home#32]
## Acceptance Criteria

- [x] Complete Contributing.md

- [x] Complete Acceptance Criteria 

- [x] Complete Task Board Entries

- [x] Complete Readme.md

- [x] Complete Product Backlog

- [x] Assign team members to various tasks/spikes

- [x] Come up with a list of questions to be asked

**Comment by bloombar** [comment]
@nyu-software-engineering/spring-2019-mta-for-google-home - this is a spike, not a user story.  Please fix the label.  Same with all the other issues that are developer issues - they are spikes and should be accurately represented.
